# https://robertohuertas.com/2019/01/20/publish-flutter-package-with-travis/

language: dart

dart:
  - stable

os:
  - linux

sudo: false

install:
  # this is to avoid an error with pub in Travis
  - echo 'Avoid default Travis CI install step'

before_script:
  - cd ..
  - git clone --single-branch --branch stable https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - flutter channel

script:
  - cd $TRAVIS_BUILD_DIR
  - flutter packages get
#  - flutter analyze --no-pub --no-current-package lib test example
  - flutter test --coverage
#  - flutter packages pub publish --dry-run
  - curl -o codecov https://codecov.io/bash
  - bash codecov

# We don't need these yet, first I want the tests to run.

#before_deploy:
#  - chmod +x ./.travis/publish.sh # giving execution permissions to this file to avoid error 127.
#  - mv ./.travis ../ # moving this out the publication folder as we don't want to publish it.
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: '../.travis/publish.sh'
#  on:
#    tags: true

cache:
  directories:
    - $HOME/.pub-cache